Fix PathFollowCommand requirements
lobstahbots/2023-Robot-Code pull request #23
Opened 2023-02-07 07:10 UTC by aidan-mundy

2023-02-07 11:49 UTC, citrus-melon requested changes

2023-02-07 11:49 UTC, citrus-melon commented on src/main/java/frc/robot/commands/drive/PathFollowCommand.java
> -        true
This line was to enable `useAllianceColor`, PathPlanner's automatic path mirroring. Looks like it accidentally got removed.

2023-02-08 16:43 UTC, kchenturtles approved these changes
Looks good

2023-02-08 20:04 UTC, citrus-melon approved these changes

2023-02-08 23:04 UTC, merged